name: Gatsby Publish

on:
  workflow_dispatch:
  push:
    branches: !master
    paths-ignore: 
      - README.md
      - .github/workflows/gatsby-deploy.yaml
      - .github/workflows/gatsby-deploy-preview.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
      - name: Install claat tool
        run: go get github.com/googlecodelabs/tools/claat
      - run: rm ./static/CNAME
      - run: yarn
      - run: yarn build
        env:
          GOOG_SA_EMAIL: ${{ secrets.GOOG_SA_EMAIL }}
          GOOG_SA_KEY: ${{ secrets.GOOG_SA_KEY }}
          GOOG_FOLDER_ID: ${{ secrets.GOOG_FOLDER_ID }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GIT_PAT }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
          repository-name: mikeacjones/syntax-sugar-preview
