name: Gatsby Publish

on:
  push:
    paths-ignore:
      - 'README.md'
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rm ./static/CNAME && echo syntaxsugar.io >> ./static/CNAME
      - run: yarn
      - run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true