name: Gatsby Publish

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
      - name: Install claat tool
        run: go get github.com/googlecodelabs/tools/claat
      - run: rm ./static/CNAME && echo syntaxsugar.io >> ./static/CNAME
      - run: yarn
      - run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
