name: Gatsby Publish

on:
  workflow_dispatch:
  push:
    branches: master
    paths-ignore: 
      - README.md
      - .github/workflows/gatsby-deploy.yaml
      - .github/workflows/gatsby-deploy-preview.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: rm ./static/CNAME && echo syntaxsugar.io >> ./static/CNAME
      - run: yarn
      - run: yarn build
        env:
          GOOG_SA_EMAIL: ${{ secrets.GOOG_SA_EMAIL }}
          GOOG_SA_KEY: ${{ secrets.GOOG_SA_KEY }}
          GOOG_FOLDER_ID: ${{ secrets.GOOG_FOLDER_ID }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
